services:
  - type: web
    name: primetrust
    runtime: python
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DEFAULT_FROM_EMAIL
        value: "PrimeTrust <noreply@primetrust.com>"
      - key: BREVO_API_KEY
        sync: false  # Set this manually in dashboard
      - key: META_SITE_DOMAIN
        value: "primetrust.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: primetrust_db
          property: connectionString
    
databases:
  - name: primetrust_db
    plan: starter