# Generated by Django 4.2.7 on 2025-07-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookendpoint',
            name='email_notifications_enabled',
            field=models.BooleanField(default=False, help_text='Send email notifications for webhook events'),
        ),
    ]
