# Generated by Django 5.2.1 on 2025-06-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_city_userprofile_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verification_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verification_code_created_at',
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_question',
            field=models.CharField(blank=True, choices=[('mother_maiden', "What is your mother's maiden name?"), ('pet_name', "What was your first pet's name?"), ('birth_city', 'In what city were you born?'), ('school_name', 'What was the name of your first school?'), ('favorite_color', 'What is your favorite color?'), ('favorite_food', 'What is your favorite food?')], max_length=50, null=True),
        ),
    ]
