# Generated by Django 5.1.3 on 2025-06-01 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be in US format: (555) 123-4567 or international format: +999999999.', regex='^(\\(\\d{3}\\) \\d{3}-\\d{4}|\\+?1?\\d{9,15})$')]),
        ),
    ]
