# Generated by Django 5.2.1 on 2025-07-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_transaction_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='transaction_pin',
        ),
    ]
