# Generated by Django 5.2.1 on 2025-07-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userprofile_transaction_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='transaction_pin',
            field=models.CharField(blank=True, help_text='4-digit PIN used for transaction verification', max_length=128, null=True),
        ),
    ]
