# Generated by Django 4.2.7 on 2025-07-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_securityrule_customuser_gender_userdevice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='login_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
