# Generated by Django 5.1.3 on 2025-05-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='routing_number',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
