# Generated by Django 5.2.1 on 2025-07-02 09:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_bitcoinwallet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoinwallet',
            name='btc_price_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='bitcoinwallet',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='bitcoin_qr_codes/'),
        ),
        migrations.AlterField(
            model_name='bitcoinwallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
