# Generated by Django 5.2.1 on 2025-07-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_bitcoinwallet_btc_price_usd_bitcoinwallet_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoinwallet',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bitcoinwallet',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
