# Generated by Django 5.2.1 on 2025-07-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_bitcoinwallet_is_active_alter_bitcoinwallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoinwallet',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='Upload QR code image for this wallet address', null=True, upload_to='bitcoin_qr_codes/'),
        ),
    ]
