# Generated by Django 5.2.1 on 2025-07-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_alter_bitcoinwallet_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance_source',
            field=models.CharField(blank=True, choices=[('fiat', 'Fiat Balance'), ('bitcoin', 'Bitcoin Balance')], help_text='Source of funds for Bitcoin transactions', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bitcoin_address',
            field=models.CharField(blank=True, help_text='Bitcoin wallet address for crypto transactions', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bitcoin_amount',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Amount in Bitcoin for crypto transactions', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bitcoin_tx_hash',
            field=models.CharField(blank=True, help_text='Bitcoin transaction hash', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('payment', 'Payment'), ('bitcoin_send', 'Bitcoin Send')], max_length=20),
        ),
    ]
