# Generated by Django 5.2.1 on 2025-07-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_transaction_balance_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='balance_source',
            field=models.CharField(blank=True, choices=[('fiat', 'Fiat Balance'), ('bitcoin', 'Bitcoin Balance'), ('admin', 'Admin Credit')], help_text='Source of funds for Bitcoin transactions', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('payment', 'Payment'), ('bitcoin_send', 'Bitcoin Send'), ('bitcoin_deposit', 'Bitcoin Deposit')], max_length=20),
        ),
    ]
